language: go
sudo: false
go:
  - 1.11.x
  - 1.x

cache:
  directories:
    - $HOME/.cache/go-build
    - $HOME/gopath/pkg/mod
    - $HOME/Library/Caches/go-build

os:
  - linux
  - osx

install:
  - go get -v -d -t ./...
  - npm --prefix client install
  - go env

script:
  - (cd `go env GOPATH`/src/github.com/prometheus/client_golang && git checkout -q v0.8.0)
  - go test ./...
  - make

