'name': 'lint'

'env':
  'GO_VERSION': '1.24.6'

'on':
  'push':
    'tags':
    - 'v*'
    'branches':
    - '*'
  'pull_request':

'concurrency':
  'group': lint_${{ github.event.head_commit.id }}
  'cancel-in-progress': true

'jobs':
  'go-lint':
    'runs-on': 'ubuntu-latest'
    'steps':
    - 'uses': 'actions/checkout@v2'
    - 'name': 'Set up Go'
      'uses': 'actions/setup-go@v3'
      'with':
        'go-version': '${{ env.GO_VERSION }}'
    - 'name': 'run-lint'
      'run': >
        make go-deps go-tools go-lint

  'eslint':
    'runs-on': 'ubuntu-latest'
    'steps':
    - 'uses': 'actions/checkout@v2'
    - 'name': 'Install modules'
      'run': 'npm --prefix="./client" ci'
    - 'name': 'Run ESLint'
      'run': 'npm --prefix="./client" run lint'